# Portia PM Agent Workflow Configuration

# Storage and Data Management
storage_dir: "workflow_data"
auto_save: true
backup_enabled: true

# Portia Integration
portia_api_key: ""  # Set via environment variable PORTIA_API_KEY

# Email Notifications (optional)
email_enabled: false
email_smtp_server: "smtp.gmail.com"
email_username: ""
email_password: ""

# Database Integration (optional)
database_enabled: false
database_url: ""

# Logging
log_level: "INFO"

# Workflow Settings
default_project_templates:
  - "web_app"
  - "mobile_app"
  - "api_service"

# Auto-transition settings
auto_transition_to_assignment: false
auto_assign_tasks: false

# Export settings
default_export_format: "json"
export_include_history: true
export_include_config: true
